---
- name: 'Create compose file: {{ nim_waku_cont_name }}'
  template:
    src: 'docker-compose.yml.j2'
    dest: '{{ nim_waku_cont_vol }}/docker-compose.yml'
    owner: dockremap
    group: docker
    mode: 0664

- name: 'Create container: {{ nim_waku_cont_name }}'
  docker_compose:
    project_src: '{{ nim_waku_cont_vol }}'
    pull: true
    state: '{{ compose_state }}'
    restarted: '{{ true if nim_waku_config.changed else compose_restart }}'
    recreate: '{{ compose_recreate }}'
    # Avoid deprecation warning
    tls_hostname: 'localhost'
