---
- name: 'Create db and config folders'
  file:
    dest: '{{ item }}'
    state: 'directory'
    owner: dockremap
    group: docker
    mode: 0775
  with_items:
    - '{{ nim_waku_node_conf_path }}'
    - '{{ nim_waku_node_db_path }}'

- name: Create script for calling REST API
  template:
    src: 'api.sh.j2'
    dest: '{{ nim_waku_cont_vol }}/api.sh'
    owner: dockremap
    group: docker
    mode: 0755

- name: 'Create compose file: {{ nim_waku_cont_name }}'
  template:
    src: 'docker-compose.yml.j2'
    dest: '{{ nim_waku_cont_vol }}/docker-compose.yml'
    owner: dockremap
    group: docker
    mode: 0664

- name: 'Create container: {{ nim_waku_cont_name }}'
  docker_compose:
    project_src: '{{ nim_waku_cont_vol }}'
    pull: true
    state: '{{ compose_state }}'
    restarted: '{{ true if nim_waku_config.changed else compose_restart }}'
    recreate: '{{ compose_recreate }}'
    # Avoid deprecation warning
    tls_hostname: 'localhost'
