---
- import_tasks: checks.yml
- import_tasks: install.yml
- import_tasks: nodekey.yml
- import_tasks: config.yml
- import_tasks: docker.yml
- import_tasks: query.yml
- import_tasks: consul.yml
- import_tasks: monitor.yml
  when: nim_waku_monitor_enabled
