---
- name: 'Wait for REST port to be available'
  wait_for:
    port: '{{ nim_waku_rest_port }}'
    delay: 5

- name: 'Extract address of the node for Consul'
  uri:
    url: 'http://localhost:{{ nim_waku_rest_port }}/debug/v1/info'
    status_code: 200
    body_format: json
  register: waku_info
  ignore_errors: true

- name: Verify we got the node address
  assert:
    that: 'waku_info.json.listenAddresses is defined'
    fail_msg: 'Did not receive Nim-Waku node address!'
    quiet: true

- name: Extract LibP2P TCP address from list
  set_fact:
    nim_waku_libp2p_enr_uri: |-
      {{ waku_info.json.enrUri }}
    nim_waku_libp2p_multiaddr: |-
      {{ waku_info.json.listenAddresses
      | reject("contains", "/ws") | first }}

- name: Extract LibP2P WS address from list
  when: nim_waku_websocket_enabled
  set_fact:
    nim_waku_libp2p_websocket: |-
      {{ waku_info.json.listenAddresses
      | select("contains", "/ws") | first }}

- name: Extract peer ID from API response
  set_fact:
    nim_waku_peer_id: '{{ nim_waku_libp2p_multiaddr.split("/") | last }}'

- name: Prepare websocket multiaddress
  when: nim_waku_websocket_enabled
  set_fact:
    nim_waku_websocket_multiaddr: '/dns4/{{ nim_waku_websocket_domain | mandatory }}/tcp/{{ nim_waku_websock_port }}/wss/p2p/{{ nim_waku_peer_id }}'

- name: Gather container info
  docker_container_info:
    name: '{{ nim_waku_cont_name }}'
  register: nim_waku_cont
