FROM python:3.9.18-alpine3.18

ENV QUERY_DELAY=60
ENV STORE_NODES=""
ENV CLUSTER_ID=1
ENV SHARD_ID=1
ENV HEALTH_THRESHOLD=5

EXPOSE {{ nim_waku_sonda_metrics_port }}

WORKDIR /opt

COPY sonda.py /opt/sonda.py

RUN pip install requests argparse prometheus_client

CMD python -u /opt/sonda.py --delay-seconds=$QUERY_DELAY --pubsub-topic=/waku/2/rs/$CLUSTER_ID/$SHARD_ID --store-nodes=$STORE_NODES --health-threshold=$HEALTH_THRESHOLD